### ISSUE TITLE
Bug in Shiboken2Config.cmake.in ?

### ISSUE THREAD

**Issue by gbaty** [PySide/shiboken2#27]
On my system, PYTHON_SUFFIX variable is always empty. 
I don't know where is definition but I think the right variable name is "PYTHON_EXTENSION_SUFFIX" instead of "PYTHON_SUFFIX".

See [data/Shiboken2Config.cmake.in:3](https://github.com/PySide/shiboken2/blob/master/data/Shiboken2Config.cmake.in#L3)

**Comment by thopiekar** [comment]
PR https://github.com/PySide/shiboken2/pull/26 should fix this.
I'll merge it now, as it worked for me. Please give feedback on that.

**Comment by gbaty** [comment]
It works. Thanks
Maybe adding quotes could be safer:
SET(PYTHON_EXTENSION_SUFFIX "@PYTHON_EXTENSION_SUFFIX@")

**Comment by thopiekar** [comment]
Makes sense... It will be replace later with the generated PYTHON_EXTENSION_SUFFIX string, so you are correct the resulting file should have the line:
```    SET(PYTHON_EXTENSION_SUFFIX "-python2.7")```
for example.

Have you tried it out with ""?

**Comment by thopiekar** [comment]
I'm also interested whether you get this: https://github.com/PySide/pyside2/issues/54

**Comment by gbaty** [comment]
Not yet. For the moment build fails on bug similar to issue PySide/pyside2#51
