### ISSUE TITLE
During build: libxml/xpath.h: No such file or directory

### ISSUE THREAD

**Issue by thopiekar** [PySide/shiboken2#38]
```
[ 76%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/docparser.cpp.o
cd /«PKGBUILDDIR»/build-3.4-dbg/ApiExtractor && /usr/bin/x86_64-linux-gnu-g++   -DQT_CORE_LIB -DQT_PLUGIN -DQT_SHARED -DQT_XML_LIB -DRXX_ALLOCATOR_INIT_0 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -Wall -fvisibility=hidden -Wno-strict-aliasing -g -I/«PKGBUILDDIR»/ApiExtractor -I/«PKGBUILDDIR»/build-3.4-dbg/ApiExtractor -I/«PKGBUILDDIR»/ApiExtractor/parser -I/«PKGBUILDDIR»/ApiExtractor/parser/rpp -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml    -fPIC -fPIC -o CMakeFiles/apiextractor.dir/docparser.cpp.o -c /«PKGBUILDDIR»/ApiExtractor/docparser.cpp
In file included from /«PKGBUILDDIR»/ApiExtractor/docparser.cpp:29:0:
/usr/include/libxslt/xsltutils.h:19:26: fatal error: libxml/xpath.h: No such file or directory
compilation terminated.
ApiExtractor/CMakeFiles/apiextractor.dir/build.make:777: recipe for target 'ApiExtractor/CMakeFiles/apiextractor.dir/docparser.cpp.o' failed
make[4]: *** [ApiExtractor/CMakeFiles/apiextractor.dir/docparser.cpp.o] Error 1
make[4]: *** Waiting for unfinished jobs....
```

```libxml2-dev``` is installed but the header is still not found during build.
* https://launchpadlibrarian.net/242236780/buildlog_ubuntu-wily-amd64.shiboken2_2.0.0.dev0-0~201602231546~rev1605~pkg23~ubuntu15.10.1_BUILDING.txt.gz
* https://packages.debian.org/de/stretch/amd64/libxml2-dev/filelist

**Comment by olear** [comment]
```
CXXFLAGS="-I${SOME_PATH}/include/libxml2" cmake <whatever>
```
Works for me.

**Comment by thopiekar** [comment]
That's a good workaround, but the real reason is a change made by @ctismer many weeks ago.

Hr had to change a variable name, which usually provides the path that needs to be included. There is no documentation about his need to rename it so I didn't merge fix, which is already there as PR.

But I have an idea to keep @ctismer 's work and make the fix working, too.

**Comment by f3nix** [comment]
Hi,
fixed by https://github.com/PySide/shiboken2/commit/1333f7eb935c2a2f7a895d48ef5b45c781f3394f

Ubuntu: https://launchpad.net/~thopiekar/+archive/ubuntu/pyside-git/+packages
Travis: ![image](https://cloud.githubusercontent.com/assets/72836/14231420/cd26d4b0-f982-11e5-9ea1-763771aa9a7f.png)

Cheers,
Mateusz
